[build]
command = "gulp build"
publish = "build"

[build.environment]
NODE_VERSION = "16"
AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[functions]
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-sitemap"

[[plugins]]
package = "./plugin"

[[redirects]]
from = "/here"
to = "/there"
force = false
  [redirects.conditions]
  Country = ["it"]

[[headers]]
for = "/blue"
  [headers.values]
  TEST = '''
  red,
  green'''

[[headers]]
for = "/gray"
  [headers.values]
  TEST = "color"
  TEST_THREE = ["color_three", "color_three_three"]

[[headers]]
for = "/gray"
  [headers.values]
  TEST = "colour"
  TEST_TWO = "colour_two"
