[build]
command = "gulp build && ls /opt/build/repo/.netlify/ && ls /opt/build/repo/.netlify/cached_plugins && ls /opt/build/repo/.netlify/cached_plugins/node_modules && du -hs /opt/build/repo/.netlify/cached_plugins/node_modules && du -hs /opt/build/repo/.netlify/cached_plugins/node_modules/*"
functions = "functions"
publish = "build"

[build.environment]
NODE_VERSION = "12"
AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[plugins]]
package = "@netlify/plugin-sitemap"
