[build]
  publish = "build"
  command = "gulp build"
  functions = "functions"
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"
  NODE_VERSION = "12"
  ZISI_VERSION = "0.4.0-3"
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
