build:
  lifecycle:
    onInit: echo HELLO $HELLO HELLO
  publish: build
  functions: functions
  environment:
    NODE_VERSION: '12'
    AWS_LAMBDA_JS_RUNTIME: nodejs10.x
    HELLO: world
  processing:
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    html:
      pretty_urls: true
    images:
      compress: true
