[build]
command = "gulp build && ls"
functions = "functions"
publish = "does-not-exist"

[build.environment]
NODE_VERSION = "12"
AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[plugins]]
package = "./plugin.js"

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
