[build]
command = "gulp build"
publish = "build"

[build.environment]
NODE_VERSION = "16"

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[plugins]]
package = "@netlify/plugin-sitemap"
