build:
  #lifecycle:
  #  onBuild: gulp build
  #publish: build
  #functions: functions
  base: src
  command: pwd
  environment:
    AWS_LAMBDA_JS_RUNTIME: nodejs10.x
    NODE_VERSION: '12'
  processing:
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    html:
      pretty_urls: true
    images:
      compress: true
