build:
  lifecycle:
    build: gulp build
  publish: build
  functions: functions
  environment:
    AWS_LAMBDA_JS_RUNTIME: nodejs10.x
  processing:
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    html:
      pretty_urls: true
    images:
      compress: true
