build:
  lifecycle:
    onInit: pwd
    onBuild: gulp build
  publish: build
  functions: functionsDoesNotExist
  environment:
    NODE_VERSION: '12'
    AWS_LAMBDA_JS_RUNTIME: nodejs10.x
  processing:
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    html:
      pretty_urls: true
    images:
      compress: true
