build:
  command: "gulp build"
  functions: "functions"
  publish: "build"
  environment:
    NODE_VERSION: "12"
    AWS_LAMBDA_JS_RUNTIME: "nodejs10.x"
plugins:
  - package: "@netlify/plugin-sitemap"
