build:
  command: gulp build
  functions: functions
  publish: build
  lifecycle:
    onInvalid: test
  environment:
    NODE_VERSION: '12'
    AWS_LAMBDA_JS_RUNTIME: nodejs10.x
  processing:
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    html:
      pretty_urls: true
    images:
      compress: true
