build:
  command: gulp build
  functions: functions
  publish: build
  environment: {}
  processing:
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    html:
      pretty_urls: true
    images:
      compress: true
