build:
  lifecycle:
    onInit: echo $YO $BUILD_ID
    onBuild: gulp build
  publish: build
  functions: functions
  environment:
    NODE_VERSION: '12'
    AWS_LAMBDA_JS_RUNTIME: nodejs10.x
    YO: hello
  processing:
    css:
      bundle: true
      minify: true
    js:
      bundle: true
      minify: true
    html:
      pretty_urls: true
    images:
      compress: true
