[build]
command = "cat ~/.netlify-build-plugins/node_modules/netlify-plugin-a11y/package.json && cat ~/.netlify-build-plugins/node_modules/netlify-plugin-a11y/manifest.yml && node -p 'require(\"/opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-a11y\")'"
functions = "functions"
publish = "build"

[build.environment]
NODE_VERSION = "12"
AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[plugins]]
package = "@netlify/plugin-sitemap"

